language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 388d51f4edbdd68e7213ff980cde939dedc4aae4db7ff10d7203ece6208e87c2
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
